apiVersion: v1
kind: Pod
metadata:
  name: pod-secretenv
spec:
  containers:
  - name: shell
    image: centos:7
    env:
      - name: SECRET_APIKEY
        valueFrom:
          secretKeyRef:
            name: apikey
            key: apikey.txt
    command:
      - "bin/bash"
      - "-c"
      - "sleep 10000"
    