apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: frontend-1
  labels:
    app: guestbook-rs
    tier: frontend
    nome: denis
spec:
  # modify replicas according to your case
  replicas: 2
  # In this case, it’s more or less the same as when we were 
  # creating the ReplicationController, except we’re using 
  # matchExpressions instead of label.
  selector:
    matchLabels:
      app: guestbook
      env: dev
  template:
    metadata:
      labels:
        app: guestbook
        env: dev
    spec:
      containers:
      - name: php-redis
        image: gcr.io/google_samples/gb-frontend:v3