apiVersion: v1
kind: Service
metadata:
  name: redis-service
spec:
  #type: NodePort
  ports:
    - name: redis-port
      #nodePort: 30100
      port: 6380
      targetPort: 6380
  selector:
    app: redis-pod