apiVersion: v1
kind: Service
metadata:
  name: wordpress-service
spec:
  type: NodePort
  ports:
    - name: http
      port: 80
      targetPort: 80  
      nodePort: 30080 
  selector:
    app: wordpress-pod