apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-pvc  
spec:
  storageClassName: manual
  accessModes:
  - ReadWriteOnce
  resources:
     limits:
       storage: 10Mi
     requests:
       storage: 10Mi
 # The selector field defines all labels necessary in a PV in order to match this claim
 #selector: 
 #  matchLabels:
 #    storage-type: nfs