apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-pvc  
spec:
  storageClassName: manual
  accessModes:
  - ReadWriteMany      
  resources:
     limits:
       storage: 1Gi
     requests:
       storage: 1Gi 
 # The selector field defines all labels necessary in a PV in order to match this claim
  selector: 
    matchLabels:
      storage-type: nfs