apiVersion: v1
kind: Service
metadata:
  name: mysql-service
spec:
  type: ClusterIP
  ports:
    - name: mysql
      # The port that will be exposed by this service.
      port: 3306
      # Number or name of the port to access on the pods targeted by the service
      targetPort: 3306
  selector:
    app: mysql-pod